/**
 * Pact Provider verification test.
 *
 * Runs against the actual provider (or a local stub) to verify it honours
 * the pact file generated by the consumer test.
 *
 * In CI: the provider team runs this against their real service.
 * Locally: point PAYMENT_PROCESSOR_URL at a stub or sandbox environment.
 *
 * This demonstrates the "provider side" of contract testing — the methodology
 * is identical to verifying an EHR system honours a lab-results contract.
 */
const { Verifier } = require('@pact-foundation/pact');
const path = require('path');

// Skip provider verification if no provider URL is configured
// (consumer tests always run; provider tests require the provider to be available)
const PROVIDER_URL = process.env.PAYMENT_PROCESSOR_URL;

const describeOrSkip = PROVIDER_URL ? describe : describe.skip;

describeOrSkip('PaymentProcessor — provider verification', () => {
  test('honours the FintechAPI consumer pact', async () => {
    const opts = {
      provider: 'PaymentProcessor',
      providerBaseUrl: PROVIDER_URL,

      // Load pact from local file (or broker if PACT_BROKER_URL is set)
      ...(process.env.PACT_BROKER_URL
        ? {
            pactBrokerUrl: process.env.PACT_BROKER_URL,
            pactBrokerToken: process.env.PACT_BROKER_TOKEN,
            consumerVersionSelectors: [{ mainBranch: true }, { deployedOrReleased: true }],
            publishVerificationResult: process.env.CI === 'true',
            providerVersion: process.env.GIT_COMMIT ?? '0.0.0-local',
          }
        : {
            pactUrls: [path.resolve(__dirname, '../../../pacts/FintechAPI-PaymentProcessor.json')],
          }),

      // State handlers — set up provider state before each interaction
      stateHandlers: {
        'a valid payment method token exists': async () => {
          // In a real test, seed the provider's test DB or configure its sandbox
          return Promise.resolve();
        },
        'the payment method will be declined': async () => {
          return Promise.resolve();
        },
        'charge ch_test_abc123 exists': async () => {
          return Promise.resolve();
        },
      },

      logLevel: 'warn',
    };

    const output = await new Verifier(opts).verifyProvider();
    console.log('Pact verification output:', output);
  }, 60000);
});
